rent_movie_main:
    path:     /main
    defaults: { _controller: RentMovieBundle:Default:main }
rent_movie_logout:
    path:     /logout
    defaults: { _controller: RentMovieBundle:Default:logout }
rent_movie_borrow:
    path:     /borrow
    defaults: { _controller: RentMovieBundle:Default:borrow }
rent_movie_borrowed:
    path:     /borrowed
    defaults: { _controller: RentMovieBundle:Default:borrowed }
rent_movie_orders:
    path:     /orders
    defaults: { _controller: RentMovieBundle:Default:orders }
rent_movie_register:
    path:     /registration
    defaults: { _controller: RentMovieBundle:Default:registration }
rent_movie_pride:
    path:     /1
    defaults: { _controller: RentMovieBundle:Default:pride }
rent_movie_game:
    path:     /5
    defaults: { _controller: RentMovieBundle:Default:game }
rent_movie_bean:
    path:     /9
    defaults: { _controller: RentMovieBundle:Default:bean }
rent_movie_mind:
    path:     /8
    defaults: { _controller: RentMovieBundle:Default:mind }
rent_movie_words:
    path:     /10
    defaults: { _controller: RentMovieBundle:Default:words }
rent_movie_penguins:
    path:     /2
    defaults: { _controller: RentMovieBundle:Default:penguins }
rent_movie_dragon:
    path:     /4
    defaults: { _controller: RentMovieBundle:Default:dragon }
rent_movie_sinister:
    path:     /3
    defaults: { _controller: RentMovieBundle:Default:sinister }
rent_movie_conjuring:
    path:     /7
    defaults: { _controller: RentMovieBundle:Default:conjuring }
rent_movie_hobbitOne:
    path:     /11
    defaults: { _controller: RentMovieBundle:Default:hobbitOne }
rent_movie_hobbitTwo:
    path:     /12
    defaults: { _controller: RentMovieBundle:Default:hobbitTwo }
rent_movie_lucy:
    path:     /6
    defaults: { _controller: RentMovieBundle:Default:lucy }
rent_movie_melodramaGenre:
    path:     /melodramaGenre
    defaults: { _controller: RentMovieBundle:Default:melodrama}
rent_movie_comedyGenre:
    path:     /comedyGenre
    defaults: { _controller: RentMovieBundle:Default:comedy}
rent_movie_dramaGenre:
    path:     /dramaGenre
    defaults: { _controller: RentMovieBundle:Default:drama}
rent_movie_horrorGenre:
    path:     /horrorGenre
    defaults: { _controller: RentMovieBundle:Default:horror}
rent_movie_fantasyGenre:
    path:     /fantasyGenre
    defaults: { _controller: RentMovieBundle:Default:fantasy}
rent_movie_scienceGenre:
    path:     /scienceGenre
    defaults: { _controller: RentMovieBundle:Default:science}
rent_movie_cartoonGenre:
    path:     /cartoonGenre
    defaults: { _controller: RentMovieBundle:Default:cartoon}
rent_movie_form:
    path:     /form
    defaults: { _controller: RentMovieBundle:Default:form}
rent_movie_mail:
    path:     /mail
    defaults: { _controller: RentMovieBundle:Default:mail}